import styles from '../styles/HomePage.module.css'
import Head from 'next/head'
import Image from 'next/image'

const About = () => {
    return (
        <>
            <Head>
                <title>About | EZScale</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <p className={styles.ph2}>
                India’s largest full-stack SME platform
            </p>

            <p className={styles.pz}>
                Our mission is to make MSMEs, truly enterprising
            </p>

            <p className={styles.p}>
                Micro-entrepreneurs, startups, MSMEs use EZScale to instantly start, sell, manage and grow, using our suite of offerings like payments, free online store, logistics, credit, and financing, and more, across mobile &amp; web.
            </p>

            <p className={styles.pz2}>
                Over 1,500,000+ MSMEs from 29 States and 7 Union Territories with 100+ million customers<br /> have used EZScale
            </p>

            <p className={styles.p}>


                <b>Rajat</b>, <b>Harshita</b> and <b>Deepak</b> started EZScale to solve one problem – make the internet a trustworthy place for a business to grow.
            </p>
            <div className={styles.pics}>
                <div className={styles.person}>
                    <Image alt="" src="/rajat.jpeg" className={styles.picture} width="90px" height="90px" />
                    <div>
                        <h2 className={styles.name}>Rajat Shenoy</h2>
                        <h3 className={styles.title}>CTO</h3>
                        <ul className={styles.ul}>
                            <li>10 years post MBA experience in Strategy &amp; Finance (Monitor Group, Merrill Lynch Investment)</li>
                            <li>B.Tech., SPIT, Mumbai</li>
                        </ul>
                    </div>
                </div>
                <div className={styles.person}>
                    <Image alt="" src="/harshita.jpeg" className={styles.picture} width="90px" height="90px" />
                    <div>
                        <h2 className={styles.name}>Harshita Lakhotiya</h2>
                        <h3 className={styles.title}>CEO</h3>
                        <ul className={styles.ul}>
                            <li>10 years post MBA experience in Strategy &amp; Finance (Monitor Group, Merrill Lynch Investment)</li>
                            <li>B.Tech., SPIT, Mumbai</li>
                        </ul>
                    </div>
                </div>
                <div className={styles.person}>
                    <Image alt="" src="/deepak.jpeg" className={styles.picture} width="90px" height="90px" />
                    <div>
                        <h2 className={styles.name}>Deepak Yadav</h2>
                        <h3 className={styles.title}>CFO</h3>
                        <ul className={styles.ul}>
                            <li>10 years post MBA experience in Strategy &amp; Finance (Monitor Group, Merrill Lynch Investment)</li>
                            <li>B.Tech., SPIT, Mumbai</li>
                        </ul>
                    </div>
                </div>
            </div>

        </>
    )
}

export default About
