import styles from '../styles/HomePage.module.css'
import Head from 'next/head'

const Home = () => {
    return (
        <>
            <Head>
                <title>EZScale</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <p className={styles.p}>
                In literary theory, a text is any object that can be &quot;read&quot;, whether this object is a work of literature, a street sign, an arrangement of buildings on a city block, or styles of clothing. It is a coherent set of signs that transmits some kind of informative message.
            </p>
        </>
    )
}

export default Home
